language: java

jdk:
  - openjdk15
cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - tixtix320@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
